accordion/urls.py
from django.urls import path
from . import views

app_name = 'accordion'

urlpatterns = [
    path('', views.showAccordion, name='showAccordion'),
]

formsStory7/urls.py
from django.urls import path
from . import views

app_name = 'formsStory7'

urlpatterns = [
    path('showforms/', views.showForms, name='showForms'),
    path('showforms/confirmation/', views.confirmation, name='confirmation'),
    path('/<int:pkTarget>/', views.changeColor, name='changeColor'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('formsStory7.urls')),
    path('', include('accordion.urls')),
    
]

accordion/models.py
from django.db import models

# Create your models here.

formsStory7/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
class Person(models.Model):
    nama = models.CharField('Nama', max_length=50)
    pesan = models.TextField('Pesan')
    warnaR = models.CharField('Warna Red', max_length=50, default='0')
    warnaG = models.CharField('Warna Green', max_length=50, default='0')
    warnaB = models.CharField('Warna Blue', max_length=50, default='0')
    
    def __str__(self):
        return self.nama

formsStory7/forms.py
from django import forms
from django.forms import ModelForm
from .models import Person

class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = ['nama', 'pesan']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
        }
        )

accordion/views.py
from django.shortcuts import render

# Create your views here.
def showAccordion(request):
    return render(request, 'accordion.html')

formsStory7/views.py
from django.shortcuts import render, redirect
from .models import Person
from .forms import PersonForm
import random

# Create your views here.
def showForms(request):
    if request.method == 'POST':
        form = PersonForm(request.POST)
        if form.is_valid():
            nama = request.POST['nama']
            pesan = request.POST['pesan']
            warnaR = str(random.randint(0,255))
            warnaG = str(random.randint(0,255))
            warnaB = str(random.randint(0,255))
            Person.objects.create(nama = nama,pesan = pesan, warnaR = warnaR, warnaG = warnaR, warnaB = warnaB)

    dataPerson = Person.objects.all()
    form = PersonForm()

    return render(request, 'formsToFill.html', {'person':dataPerson, 'form':form})

def confirmation(request):
    if request.method == 'POST':
        form = PersonForm(request.POST)
        return render(request, 'confirmation.html', {'nama':form.data['nama'], 'pesan':form.data['pesan']})

def changeColor(request, pkTarget):
    target = Person.objects.get(pk = pkTarget)
    target.warnaR = str(random.randint(0,255))
    target.warnaG = str(random.randint(0,255))
    target.warnaB = str(random.randint(0,255))
    
    target.save()

    dataPerson = Person.objects.all()
    return redirect('formsStory7:showForms')

accordion/templates/accordion.html
{% extends 'includes/base2.html' %}
{% load static %}

{% block title %}Accordion{% endblock %}

{% block body %}
    <div class="container">

        <div class="accor1 accordion">
            <h3>Tentang Saya <span><button class="up">up</button><button class="down">down</button></button></span></h3>
            <div class="panel1 panel"><p>Halo, nama saya Sae Pasomba, namun teman-teman memanggil saya Sae. Saya lahir 24 Februari 2002 di Palangka Raya. Saya sangat senang mengamati hujan.</p></div>
        </div>

        <div class="accor2 accordion">
            <h3>Aktivitas Saat Ini <span><button class="up" name="up2">up</button><button class="down" name="down2">down</button></button></span></h3>
            <div class="panel2 panel"><p>Aktivitas saya saat ini hanya bermain game, mengerjakan tugas, dan berolah raga.</p></div>
        </div>

        <div class="accor3 accordion">
            <h3>Pengalaman Organisasi/Kepanitiaan <span><button class="up">up</button><button class="down">down</button></button></span></h3>
            <div class="panel3 panel">
                <p>BEM Fasilkom UI</p>
                <p>Mentor BETIS 2020</p>
                <p>OSIS SMA</p>
            </div>
        </div>

        <div class="accor4 accordion">
            <h3>Prestasi <span><button class="up">up</button><button class="down">down</button></button></span></h3>
            <div class="panel4 panel">
                <p>Bronze Medal Young Inventors Challenge</p>
                <p>Juara 1 Teknologi Tepat Guna, Tangerang Selatan</p>
            </div>
        </div>
    </div>

    <div class="happyButton">
        <button class="themeChanger themeChanger1">Change Theme!</button>
        <button class="accordionChanger accordionChanger1">Lame Accordion Shape?</button>
    </div>
{% endblock %}

accordion/templates/includes/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Paaji+2:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'accordion/css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    

    <title>{% block title %}{% endblock title %}</title>
</head>
<body>

    {% block body %}
    {% endblock %}

    
    <script src="{% static 'accordion/js/script.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

formsStory7/templates/confirmation.html
{% extends 'includes/base.html' %}
{% load static %}

{% block title %}Confirmation{% endblock %}

{% block body %}
    <div class="container">
        <div class="info">
            <h3>
                Apa anda yakin mengirim pesan ini?
            </h3>
            <table>
                <tr>
                    <td><p><strong>Nama</strong></p></td>
                    <td><p>:</p></td>
                    <td><p>{{nama}}</p></td>
                </tr>
                <tr>
                    <td><p><strong>Pesan</strong></p></td>
                    <td><p>:</p></td>
                    <td><p>{{pesan}}</p></td>
                </tr>
            </table>
        </div>
        <div class="submitButton">
            <div>
                <form action="/showforms/" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="nama" value="{{ nama }}">
                    <input type="hidden" name="pesan" value="{{ pesan }}">

                    <button type="submit" class="btn btn-success" value="Confirm" name="confirm">Submit</button>
                </form>
            </div>

            <div class="buffer"></div>

            <div>
                <form action="/" method="GET">
                    <button type="submit" class="btn btn-danger" value="Cancel" name="cancel">Cancel</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

formsStory7/templates/formsToFill.html
{% extends 'includes/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Pesan Mata Angin{% endblock %}

{% block body %}

    <div class="container headerName text-center">
        <h1>Selamat datang di <span id="brandName">Pesan Mata Angin</span></h1>
    </div>

    <hr>

    <div class="container formDiv">
        <form action="confirmation/" method="post" class="form-group">
            <table>
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <tr>
                    <td></td>
                    <td class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary" name="submitButton">Submit</button>
                    </td>
                </tr>
            </table>
            
        </form>
    </div>

    <hr>

    <div class="container tableData">
        <table class="table">
            {% for person in person %}
                <tr style="background-color: rgb({{ person.warnaR }}, {{ person.warnaG }}, {{ person.warnaB }});" name="messageBox">
                    <td>{{ person.nama }}</td>
                    <td>
                        <div class="buffer" style="width: 50px;"></div>
                    </td>
                    <td>{{ person.pesan }}</td>
                    <td>
                        <div class="buffer" style="width: 50px;"></div>
                    </td>
                    <td class="buttonDiv">
                        <a href="{% url 'formsStory7:changeColor' pkTarget=person.pk %}">
                            <button class="btn btn-primary" name="changeColor">Change Color</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

formsStory7/templates/includes/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'formsStory7/css/style.css' %}">

    <title>{% block title %}{% endblock title %}</title>
</head>
<body>

    {% block body %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>